Add missing jar
05-19 22:07:07.661  2632  2746 E AndroidRuntime: FATAL EXCEPTION: 
MainEventThread
05-19 22:07:07.661  2632  2746 E AndroidRuntime: Process: .dataservices, 
PID: 2632
05-19 22:07:07.661  2632  2746 E AndroidRuntime: 
java.lang.NullPointerException: Attempt to read from null array
05-19 22:07:07.661  2632  2746 E AndroidRuntime: 	at 
com.quicinc.cne.CNE$5.onChange(CNE.java:2261)